### ISSUE TITLE
Unable to get Cop Chase program V 1.2 to run properly

### ISSUE THREAD

**Issue by Orangery-DS** [SLiV9/CopChase#1]
Hi Sander.  Hope all is okay with you.

I made up about one hundred challenges for the game you coded for me but cannot seem to get it to work properly anymore.  I'm using Windows 10 and I would make up new challenges now and again and wanted to log them all.  It could be that my version of Windows is screwed up?  I have tried running in compatibility mode which seems to help but the program stalls at solving.

I can get a bit further with it on my friends computer (same operating system) but it displays a repeated error message "board blocker out of bounds" when trying to find solutions.

Also tried it on an old laptop (Vista I think) and another desktop PC running XP but the program displays "D3D create device error..." and doesn't even launch.

Any ideas or advice would be appreciated - Dave S.

**Comment by SLiV9** [comment]
Hi Dave. I just searched my backups for the last compiled version of CopChase, version 2.1 from December 1, 2013. Is that also the version you were running? If not, I've reuploaded that version here (https://github.com/SLiV9/CopChase/releases/tag/v2.1), so maybe you can give that one a try. Be sure to unzip it so that both the CopChaseGUI.exe and CopChaseSolver.exe are in the same folder.

I tried running this version on Windows 10, and it seemed to work fine. It did prompt me to install the "DirectPlay" feature for some reason, so maybe you need to install that as well. I think if you go to "Programs and Features" and then "Turn Windows features on or off", there should be an expandable group called "Legacy Features" with "DirectPlay" under it. Hope that helps!

**Comment by Orangery-DS** [comment]
Ha, I got version 1.2 version running again somehow, just a day or so before your reply.  I'm in the process of entering the solutions (output text) into a spreadsheet.  It has only taken me 8 years to do this!

You say there is a 2.1 version (the uncompressed file size is 4022 KB, which is exactly the same as V 1.2)?  Anyway, I really appreciate the time and effort you put into all of this.

Do you have any projects on the go; need any help?

Kind regards - Dave S.

**Comment by SLiV9** [comment]
Glad you got it working again! I'll close this issue for now. Ah, I think CopChaseGUI.exe is still version 1.2, but CopChaseSolver.exe (which is called by the GUI to do all the hard work) is version 2.1. I think at one point I updated the solver without making a new GUI.

I'm working on games within a worker cooperative, and our first strategy game Epicinium came out last year. We're currently also looking for paid programming gigs, so if you think of anything, let me know!
